### ISSUE TITLE
Назви змінних

### ISSUE THREAD

**Issue by detonavomek-zz** [katadoka/reverse-file-text#6]
https://github.com/katadoka/reverse-file-text/blob/d610fdf4f5a6b437a3e47c2223015a9e7d8e4f91/main.py#L6

Змінити senten на sentence

**Comment by katadoka** [comment]
https://github.com/katadoka/reverse-file-text/commit/579635dd6f27190d8a77c4a13e2f7493461de7b9#diff-5bc02cefb3ea9e27f1a6776eabd1935d

updated

**Comment by detonavomek-zz** [comment]
залишив коментар по цій силці.

до речі, якщо коміт назвати "#6 names of variables" замість "names of variables", то він автоматично буде тут відображатись.

можеш попробувати виправити коментар і в назву коміту поставити "#6 remove unnessesary tabs". потім запушити його і обновити тут сторінку. він має автоматично показуватись тут.
